language: objective-c
osx_image: xcode8.0
sudo: false
xcode_project: LJMapCoordinateCorrection.xcodeproj
xcode_scheme: LJMapCoordinateCorrection

before_install:
- env
- xcodebuild -version
- xcpretty --version

script:
- set -o pipefail
- xcodebuild clean build -project "$TRAVIS_XCODE_PROJECT"  -scheme "$TRAVIS_XCODE_SCHEME" | xcpretty
